<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sort by average rating</name>
   <tag></tag>
   <elementGuidId>e0af78e3-fc8f-43f7-97fe-8cb6e8ba63c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-orderby-ny-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-orderby-ny-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>79848442-fac9-410b-a48a-358f3feff03d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>a31cb12c-7024-4473-a34b-63b00fd3cf21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-orderby-ny-container</value>
      <webElementGuid>3af29627-75f7-4e9f-8b57-504a80b73f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sort by average rating</value>
      <webElementGuid>f297788e-f237-479a-bac6-a3d9504a1f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sort by average rating</value>
      <webElementGuid>cbd07b19-9824-4043-8a3c-a598b70acd00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-orderby-ny-container&quot;)</value>
      <webElementGuid>ede9ed30-fdcc-461f-838b-6ee38c755214</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-orderby-ny-container']</value>
      <webElementGuid>bb3ad100-7c27-4e67-a562-51a44e3a1c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/form/span/span/span/span</value>
      <webElementGuid>fd156262-ffe1-4da5-99c2-415c72bd2d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop'])[2]/following::span[4]</value>
      <webElementGuid>51fb58ef-2f09-4169-9611-a13341ceaeb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop'])[1]/following::span[4]</value>
      <webElementGuid>2ac2c0e2-16d9-4936-bc5a-0ff371427e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to cart'])[1]/preceding::span[3]</value>
      <webElementGuid>1ba1d0ee-f4c9-4ade-af31-b98da6070db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient Ninja'])[1]/preceding::span[3]</value>
      <webElementGuid>40384f3a-9a16-4cb6-97ab-f97fd2f4348f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>d6062a35-09b4-4fab-81c7-a497f866909c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-orderby-ny-container' and @title = 'Sort by average rating' and (text() = 'Sort by average rating' or . = 'Sort by average rating')]</value>
      <webElementGuid>06c6dd7c-f0b5-4831-adc6-b3f2c7d20f92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
