<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sort by popularity</name>
   <tag></tag>
   <elementGuidId>6f3ba0f1-0f51-412c-af30-34f6a2dc3cba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-orderby-lm-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-orderby-lm-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>991d32b4-6244-4434-9d59-aff217261b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>ba7fcaed-a2f7-4e99-a576-9d8a17119c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-orderby-lm-container</value>
      <webElementGuid>c2b43e7a-a912-437c-8a28-705de70e4c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sort by popularity</value>
      <webElementGuid>5fe414a5-e009-4738-ad4d-5951be6540b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sort by popularity</value>
      <webElementGuid>a29a362d-b828-4a0e-a482-6fd118220e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-orderby-lm-container&quot;)</value>
      <webElementGuid>7844b7c7-305d-4df0-b9d4-ba819290010e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-orderby-lm-container']</value>
      <webElementGuid>c0b4c21d-3882-43f7-8ce2-8fd2833d559c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/form/span/span/span/span</value>
      <webElementGuid>ba3467f1-836b-4c53-8c21-d502bd461ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop'])[2]/following::span[4]</value>
      <webElementGuid>6637b793-888a-444d-92d9-672be1d46acd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop'])[1]/following::span[4]</value>
      <webElementGuid>8be42d39-5e60-4338-9aa1-a68d30aa00b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to cart'])[1]/preceding::span[3]</value>
      <webElementGuid>d05bc8d6-19f5-4fc0-9f77-209c803235a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Woo Logo'])[1]/preceding::span[3]</value>
      <webElementGuid>0c9a7d7e-7f70-4891-bde9-c901c06a6295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>66420d4a-bbe6-4d5b-8c9b-724e47df0619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-orderby-lm-container' and @title = 'Sort by popularity' and (text() = 'Sort by popularity' or . = 'Sort by popularity')]</value>
      <webElementGuid>b1b8a78b-c43d-4809-826b-eeccaee90ce4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
