<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Default sorting</name>
   <tag></tag>
   <elementGuidId>40162a35-6fac-41a0-bd1c-3b68acf9aadc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-orderby-ns-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-orderby-ns-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f7ac8790-e397-48e6-b6e5-acd8df31f2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>e1f1f8d4-3fc9-4b23-bad8-791c8a55931d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-orderby-ns-container</value>
      <webElementGuid>cad9717c-1dc5-40bb-904a-d493fc19e79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Default sorting</value>
      <webElementGuid>9721a2df-6c5e-4b86-9420-d6f17f56a387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Default sorting</value>
      <webElementGuid>e5194131-501f-4494-983f-78dcefe53941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-orderby-ns-container&quot;)</value>
      <webElementGuid>140607e1-a9b1-4fd3-8e29-7091a285aa52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-orderby-ns-container']</value>
      <webElementGuid>7fdd1fa4-5bc8-461e-9b43-5c02a71a9ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/form/span/span/span/span</value>
      <webElementGuid>100794b9-e0dc-4a06-817c-a30c171b0ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop'])[2]/following::span[4]</value>
      <webElementGuid>c489505c-3318-41fb-be67-e97baa98e400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop'])[1]/following::span[4]</value>
      <webElementGuid>2ff38f7e-349b-4a3a-8cec-1860e2a4e7fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sale!'])[1]/preceding::span[3]</value>
      <webElementGuid>38e5453b-ccdf-484e-bd8d-8cba2ab411f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to cart'])[1]/preceding::span[4]</value>
      <webElementGuid>ec9cf5bc-4a5c-426a-a932-901815096b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>cf9814f1-3f64-4586-89e6-d9e64994af16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-orderby-ns-container' and @title = 'Default sorting' and (text() = 'Default sorting' or . = 'Default sorting')]</value>
      <webElementGuid>ac95ac3a-d290-4d5e-9f37-ee1ed3988fda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
