<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ship_to_different_address</name>
   <tag></tag>
   <elementGuidId>7a6b8381-bdfc-444b-a148-05a3144ff46e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ship-to-different-address-checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ship-to-different-address-checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>532d876a-5c9a-4311-946e-16bcbee8d293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ship-to-different-address-checkbox</value>
      <webElementGuid>ad5c8f44-2daf-47c9-9cfe-9ea6f42c35b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-form__input woocommerce-form__input-checkbox input-checkbox</value>
      <webElementGuid>9f955fcb-f8e9-47d7-9e60-22ffa1f7d6a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>321ec370-a550-428c-9942-bcdc7b38c50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ship_to_different_address</value>
      <webElementGuid>6ca1ed8f-082b-44e0-aa57-fb6335f4508b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c6d5d0d9-0f70-4074-8f0e-ab597ba4b79e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ship-to-different-address-checkbox&quot;)</value>
      <webElementGuid>0b9b175d-22f3-46fc-8784-045c7e974151</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ship-to-different-address-checkbox']</value>
      <webElementGuid>f164b19b-aadb-49b4-bf36-3a93530ba5a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h3[@id='ship-to-different-address']/label/input</value>
      <webElementGuid>4c322f7f-c3ae-4602-84fd-92b921772d09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>f945feb7-9734-4bea-a184-802564699e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ship-to-different-address-checkbox' and @type = 'checkbox' and @name = 'ship_to_different_address']</value>
      <webElementGuid>2c2390ee-0db4-48ec-853e-9e633a5a8dbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
