<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(optional)_shipping_company</name>
   <tag></tag>
   <elementGuidId>ab5a757b-14f7-4fb5-9fa0-d688cf046076</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shipping_company</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='shipping_company']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b94bd9b1-919c-4f8b-8925-97cc55d06f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7229e782-88f4-44d5-8938-e3bffacbf538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>e8242b87-08e5-4f34-97f3-82613cea945f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipping_company</value>
      <webElementGuid>6bc2936e-c9b7-49bd-bff1-4bab57dada5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shipping_company</value>
      <webElementGuid>36512468-d64d-456f-93c0-bbd169472fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>organization</value>
      <webElementGuid>a5b01137-8b61-425e-b4b1-1ee123526275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shipping_company&quot;)</value>
      <webElementGuid>8b64a45e-1da6-429a-a544-9659bde13fa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='shipping_company']</value>
      <webElementGuid>0752df06-9672-440c-a290-9b7c8fe8ab2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='shipping_company_field']/span/input</value>
      <webElementGuid>ae25e2ef-a479-493a-b38c-6507de8d4be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/p[3]/span/input</value>
      <webElementGuid>e7a54d1a-b412-498e-8710-d7b3c1714d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'shipping_company' and @id = 'shipping_company']</value>
      <webElementGuid>58d2565a-6114-4baa-9325-778b935fabaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
