<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__shipping_address_1</name>
   <tag></tag>
   <elementGuidId>28728686-3cf4-4c56-919a-801aa6839ac1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shipping_address_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='shipping_address_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>527c4a53-96f2-4995-bd40-770767b494f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>86edb4a8-cfee-45d7-8810-023abaa272de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>5f7df26b-29b6-4572-a791-5c35a6add770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipping_address_1</value>
      <webElementGuid>69c5ab3c-bc8d-4cda-94e4-b18ea11dbcd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shipping_address_1</value>
      <webElementGuid>e149647e-890d-4e74-a007-0a189cba2b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>House number and street name</value>
      <webElementGuid>4b8deb3b-a968-45ce-9de9-f5cbc27a7d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>address-line1</value>
      <webElementGuid>22292f5f-c055-40ed-b0d1-a69c148af994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>House number and street name</value>
      <webElementGuid>e27db202-b03a-4e2a-87f3-3a16efce958c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shipping_address_1&quot;)</value>
      <webElementGuid>4871a6af-299e-4901-8271-603124911e4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='shipping_address_1']</value>
      <webElementGuid>a6a93199-ce0a-42a8-a17a-81bbfbd42d65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='shipping_address_1_field']/span/input</value>
      <webElementGuid>c7b9d50a-e4da-472a-b914-05da41abc827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/p[5]/span/input</value>
      <webElementGuid>2daf0ac9-bd26-4208-a2be-baf765034863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'shipping_address_1' and @id = 'shipping_address_1' and @placeholder = 'House number and street name']</value>
      <webElementGuid>1fb8792c-d625-4cba-964e-d933b030662f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
