<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Search_ellie-icon-search</name>
   <tag></tag>
   <elementGuidId>7a221aab-c179-4c41-b139-f39c25e74457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ellie-icon-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='search-2']/form/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8db19510-3362-4b8a-8f5b-0a9103c54914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ellie-icon-search</value>
      <webElementGuid>770904ed-224c-4a71-99b2-b32eca02d6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-2&quot;)/form[@class=&quot;search-form&quot;]/button[@class=&quot;search-submit&quot;]/i[@class=&quot;ellie-icon-search&quot;]</value>
      <webElementGuid>045e1df8-4a58-4a6e-9476-003cd8e0b668</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='search-2']/form/button/i</value>
      <webElementGuid>ce3ccc86-3055-4665-8228-6af93ef9a8ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>7ba3e609-3809-4020-a7f3-653b0071c7b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
